// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.anshika.proto;

public interface StudentsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Students)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Student students = 1;</code>
   */
  java.util.List<com.anshika.proto.Student> 
      getStudentsList();
  /**
   * <code>repeated .Student students = 1;</code>
   */
  com.anshika.proto.Student getStudents(int index);
  /**
   * <code>repeated .Student students = 1;</code>
   */
  int getStudentsCount();
  /**
   * <code>repeated .Student students = 1;</code>
   */
  java.util.List<? extends com.anshika.proto.StudentOrBuilder> 
      getStudentsOrBuilderList();
  /**
   * <code>repeated .Student students = 1;</code>
   */
  com.anshika.proto.StudentOrBuilder getStudentsOrBuilder(
      int index);
}
